---

- name: configure ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^Port'
      line: 'Port {{ di_ssh_port }}'
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication {{ di_ssh_password_authentication }}'
    - regexp: '^PermitRootLogin'
      line: 'PermitRootLogin {{ di_ssh_permit_root_login }}'
    - regexp: '^AllowUsers'
      line: 'AllowUsers {{ di_ssh_allow_users }}'
  notify: restart ssh
