---

- name: install ufw package
  apt: name=ufw state=present

- name: configure ufw default policies
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
  notify: restart ufw

- name: configure ufw to allow ssh
  ufw: rule=allow port={{ di_ssh_port }} proto=tcp
  notify: restart ufw

- name: enable ufw
  ufw: state=enabled
