---

- name: install ufw package
  apt: name=ufw state=present

- name: configure ufw default policies
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
  notify: restart ufw

- name: configure user-defined ufw rules
  ufw:
    rule: '{{ item.rule }}'
    from: '{{ item.from }}'
    to: '{{ item.to }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  with_items: '{{ di_ufw_rules }}'
  notify: restart ufw

- name: enable ufw
  ufw: state=enabled
